apiVersion: v1
kind: Service
metadata:
  name: flask-service-lb
  labels:
    app: two-tier-app
spec:
  type: LoadBalancer
  selector:
    app: two-tier-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service-nodeport
  labels:
    app: two-tier-app
spec:
  type: NodePort
  selector:
    app: two-tier-app
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30080
